import projectImages from "./project-images";

const Projects = [
    {
      id: "project-1",
      title: "FreyKu.AI",
      shortDesc: "A platform for AI-powered Chatbot.",
      description: "This project is a platform for AI-powered Chatbot. It uses the OpenAI API to generate content based on the user's input.",
      tags: ["OpenAI", "Ollama", "Python", "React.js", "Next.js", "NestJS", "TypeScript", "Tailwind CSS", "Shadcn UI", "PostgreSQL"],
      imageDetails: projectImages[0],
      liveDemoUrl: null,
      codeUrl: "https://github.com/commoners1/freyku-ai-chatbot",
    },
    {
      id: "project-2",
      title: "NOTCH ERP System (In Progress)",
      shortDesc: "A unified ERP platform for NOTCH Internal Management.",
      description: "This project is a fully integrated ERP platform designed to streamline organizational operations by combining project tracking, human resources, and employee management into a single centralized system. To ensure high performance and efficient data handling, the platform incorporates Redis caching and advanced query optimization, resulting in a 45% reduction in page load times. Additionally, the system features secure attendance tracking powered by face recognition technology and includes real-time location monitoring through seamless integration with the Google Maps API.",
      tags: [
        "Next.js", 
        "Nest JS", 
        "TypeScript", 
        "Tailwind CSS", 
        "Shadcn UI", 
        "Redis", 
        "Prisma", 
        "PostgreSQL", 
        "Google Maps API", 
        "Python", 
        "Face Recognition"
      ],
      imageDetails: projectImages[1],
      liveDemoUrl: null,
      codeUrl: "https://github.com/commoners1/notch-erp",
    },
    {
      id: "project-3",
      title: "NOTCH Company Website",
      shortDesc: "An official NOTCH company website.",
      description: "This project involved developing a high-performance, SEO-optimized landing page framework for NOTCH Creative Agency, enabling rapid deployment of modern, responsive websites for multiple clients. Built with a TypeScript-driven stack using Next.js and NestJS, the system incorporates efficient server-side rendering, Redis caching, and PostgreSQL with Prisma ORM for streamlined data access. The framework includes reusable UI components and performance enhancements that improved Lighthouse scores by 35%, ensuring faster load times and stronger search visibility across all client sites.",
      tags: [
        "Next.js", 
        "TypeScript", 
        "Tailwind CSS"
      ],
      imageDetails: projectImages[2],
      liveDemoUrl: null,
      codeUrl: "https://github.com/webdevnotch/notch-company-profile",
    },
    {
      id: "project-4",
      title: "UNICEF-Salesforce Middleware System",
      shortDesc: "A platform to pool Salesforce data for UNICEF Indonesia Website.",
      description: "This project involved building a robust REST API middleware for UNICEF Indonesia to seamlessly synchronize Salesforce donation data with their public web platform. Developed using a TypeScript-based architecture with NestJS and PostgreSQL (via Prisma ORM), the system ensures secure, reliable data flow between Salesforce and client-facing interfaces. BullMQ queues were integrated to handle high-volume, concurrent donation requests with improved stability and throughput. The project also included implementing telemetry for real-time monitoring and comprehensive Jest test coverage to ensure code quality, reliability, and long-term maintainability. A companion React (Vite) dashboard was also developed to provide visibility into synchronization status and system performance.",
      tags: [
        "TypeScript",
        "NestJS",
        "React.js (Vite)",
        "Redis",
        "BullMQ",
        "PostgreSQL",
        "Prisma",
        "Jest"
      ],
      imageDetails: projectImages[3],
      liveDemoUrl: null,
      codeUrl: "https://github.com/commoners1/unicef-sf-middleware",
    },
    {
      id: "project-5",
      title: "UNICEF Indonesia Fundrasing Website",
      shortDesc: "An official fundraising website for UNICEF Indonesia.",
      description: "This project focused on maintaining and improving UNICEF Indonesia’s official fundraising website, ensuring stable and secure donation processing for thousands of users. Responsibilities included migrating legacy components to modern standards, implementing SSL for secure communications, and optimizing front-end and back-end performance to improve overall site responsiveness. The payment workflow was enhanced to comply with PCI DSS requirements, resulting in reduced transaction failures and a more reliable donation experience. Built using the Lambemu PHP framework with a modern web stack, the updated platform delivers greater stability, security, and performance for UNICEF’s online fundraising operations.",
      tags: [
        "Lambemu Framework (PHP)",
        "HTML",
        "CSS",
        "Bootstrap 4",
        "JavaScript",
        "jQuery",
        "MySQL",
        "Midtrans",
        "Xendit",
        "DOKU"
      ],
      imageDetails: projectImages[4],
      liveDemoUrl: "https://supportunicefindonesia.org",
      codeUrl: "https://github.com/commoners1/d-uncf-rdv",
    },
    {
      id: "project-6",
      title: "Vanuatu HR Parliament System",
      shortDesc: "An HR Management System for Vanuatu Parliament.",
      description: "The HR Parliament System is a comprehensive web-based Human Resource Information System designed to streamline employee management and administrative processes for parliamentary institutions. The platform provides real-time dashboards featuring employee demographics, department analytics, and work history insights through interactive charts. It includes modules for employee records, leave management, attendance tracking, user roles, and automated reporting. Built with a focus on usability and data accuracy, the system enables HR teams to manage workforce operations more efficiently, improve decision-making, and maintain clear organizational oversight.",
      tags: [
        "CodeIgniter 3",
        "PHP",
        "HTML 5",
        "CSS",
        "Bootstrap 4",
        "JavaScript",
        "jQuery",
        "MySQL"
      ],
      imageDetails: projectImages[5],
      liveDemoUrl: "https://parliamenthr.cns.com.vu/",
      codeUrl: "https://github.com/commoners1/parliamenthr",
    },
    {
      id: "project-7",
      title: "Indohajj - Tour & Travel Website",
      shortDesc: "A tour-and-travel website.",
      description: "Indohajj is a modern tour and travel website designed to streamline Umrah and Hajj registration services using a clean, user-friendly interface. The platform features detailed package listings, flight information, hotel options, and visa processing guidance to help travelers plan their pilgrimage with ease. Built to enhance trust and convenience, the system provides clear service descriptions, smooth navigation, and an accessible onboarding flow for customer registration. With a focus on delivering a seamless digital experience, Indohajj helps travelers manage the entire journey—from information lookup to booking—through an efficient online platform.",
      tags: [
        "Laravel 8",
        "PHP",
        "HTML 5",
        "CSS",
        "Bootstrap 5",
        "JavaScript",
        "AJAX",
        "MySQL"
      ],
      imageDetails: projectImages[6],
      liveDemoUrl: "https://indohajj.com",
      codeUrl: "https://github.com/08freyza/indohajj",
    },
    {
      id: "project-8",
      title: "Suds&Sparkle - Laundry System Management",
      shortDesc: "A system for laundry management & its transactions.",
      description: "Suds&Sparkle is a full-featured laundry management web system designed to streamline order processing, payments, and customer interactions for laundry businesses. The platform provides an intuitive dashboard for managing orders, tracking pickup and delivery status, and viewing detailed service information. It integrates multiple payment channels—including credit/debit cards, virtual accounts, e-wallets, and QRIS—allowing customers to conveniently complete transactions online. The system enhances operational efficiency by automating order workflows, recording service metrics, and improving transparency for both administrators and customers. Built with modern web technologies, Suds&Sparkle reduces manual effort and delivers a smooth, reliable digital experience for laundry service operations.",
      tags: [
        "Laravel 9",
        "PHP",
        "HTML 5",
        "CSS",
        "Bootstrap 5",
        "JavaScript",
        "AJAX",
        "jQuery",
        "MySQL",
        "Midtrans"
      ],
      imageDetails: projectImages[7],
      liveDemoUrl: null,
      codeUrl: "https://github.com/commoners1/sudsnsparkles",
    },
    {
      id: "project-9",
      title: "Bel Sekolah App",
      shortDesc: "An app for managing the school bell effectively and mobile.",
      description: "Bel Sekolah App is an Android & iOS application designed to simplify and automate school bell scheduling. The app allows administrators to create custom bell schedules, set precise ringing times, and import schedules across multiple days for faster setup. It includes features such as automatic bell triggering, custom ringtone selection, backup and restore options, and complete control over starting, stopping, or restarting the schedule. With an intuitive interface tailored for school staff, Bel Sekolah App makes managing daily class transitions easier, more accurate, and fully automated.",
      tags: [
        "React Native",
        "Material UI",
        "SQLite",
        "CSS",
      ],
      imageDetails: projectImages[8],
      liveDemoUrl: null,
      codeUrl: "https://github.com/08freyza/belsekolahapp",
    },
];

export default Projects